name: Generate ipynb files
on:
  push:
    branches: [ main ]
    paths:
    - 'examples/*/*.py'
    - '.github/workflows/generate_ipynb_files.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext

      - name: Generate magic-wand ipynb
        run: |
          cd examples/magic-wand
          sed 's/${EXAMPLE}/magic_wand/g' $GITHUB_WORKSPACE/.github/scripts/build_binary_in_colab.txt > replacement.txt
          cp magic_wand.py magic_wand_build_binary.py
          sed -i $'/fetch prebuilt binaries/{r replacement.txt\n d}' magic_wand_build_binary.py
          jupytext --to ipynb magic_wand.py magic_wand_build_binary.py

      - name: Generate hello-world ipynb
        run: |
          cd examples/hello-world
          sed 's/${EXAMPLE}/hello_world/g' $GITHUB_WORKSPACE/.github/scripts/build_binary_in_colab.txt > replacement.txt
          cp hello_world.py hello_world_build_binary.py
          sed -i $'/fetch prebuilt binaries/{r replacement.txt\n d}' hello_world_build_binary.py
          jupytext --to ipynb hello_world.py hello_world_build_binary.py

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: Commit and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git add examples/*/*.ipynb
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Generate ipynb files";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-zephyr-vexriscv-examples.git main
          else
            echo "no changes";
          fi
